name: Update Stock Prices

on:
  schedule:
    - cron: '30 14,20 * * 1-5'
  workflow_dispatch:

jobs:
  update-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Check Python Version
        run: python --version

      - name: Install Dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run Price Updater
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          cd backend/simps_project
          python scripts/price_updater.py
